name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  path: ^1.8.0
  expensya_annotations:
    path: ../expensya_annotations

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  expensya_gen:
    path: ../expensya_gen
  build_runner: ^2.3.3
