targets:
  $default:
    builders:
      expensya_gen|expensya_gen:
        enabled: true


builders:
  expensya_gen:
    target: ":expensya_gen"
    import: "package:expensya_gen/expensya_gen.dart"
    builder_factories: ["expensyaGenExample"]
    build_extensions: { ".dart": [".example.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
